### ISSUE TITLE
Cookbook name collides with already extant public cookbook

### ISSUE THREAD

**Issue by jeffbyrnes** [evertrue/et_elk-cookbook#9]
There is already an [elk cookbook](https://supermarket.chef.io/cookbooks/elk), and using the same name for a public & private cookbook can have dangerous results.

As a simple means of avoiding this, I propose this cookbook be renamed to `et_elk`, and, unless there is a need not to, be published to the Supermarket.

**Comment by EdHurtig** [comment]
Lol that wasn't there a few months ago

**Comment by jeffbyrnes** [comment]
Publish or die.

**Comment by EdHurtig** [comment]
probably should have published

**Comment by EdHurtig** [comment]
The Good news... this cookbook is really an EverTrue centric cookbook.  The ones that are actually important are the `elk_*` sub cookbooks

**Comment by jeffbyrnes** [comment]
@EdHurtig ah! Ok then. I’ll go about renaming this one, and when you get a chance, might be good to publish the dependency cookbooks. Do you have the necessary PEM to publish to the Supermarket as the `evertrue` user?

**Comment by EdHurtig** [comment]
@jeffbyrnes I believe I do

**Comment by jeffbyrnes** [comment]
Fixed by 250a7a1032f4ef5824f7639ab45f0b2df30c249b

**Comment by EdHurtig** [comment]
:+1:
